version: '2'
services:
  database:
    image: postgres

  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - smart_cookbook:/srv
    command: gunicorn -p 8000 -w 1 smart_cookbook.wsgi:application