# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients'),
        ),
    ]
