# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cookbook', '0002_auto_20171015_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientquantity',
            unique_together=set([('ingredient', 'recipe')]),
        ),
    ]
